name: overfit_detection
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.8.13
  - setuptools=63.4.1
  - sqlite=3.39.2
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - --extra-index-url https://pypi.org/simple
    - fastdtw==0.3.4
    - numpy==1.21.5
    - pandas==1.4.3
    - pyts==0.12.0
    - scikit-learn==0.24.2
    - scipy==1.7.3
    - sequentia==0.13.1
    - matplotlib==3.6.0
